### ISSUE TITLE
api routes are not pre-renderable 😕 

### ISSUE THREAD

**Issue by JaKXz** [josh-collinsworth/sveltekit-blog-starter#10]
Just want to point this out because I think the build step is currently broken [with the latest HEAD at time of writing], but I'm curious if you're seeing different results.

Trying to figure out how to get sveltekit's prerendering to ignore all my api/ routes because they're not prerenderable?
I've set:
```js
export const prerender = 'auto'
``` 
in my +layout.js hoping that would figure out the difference? `true` and `'auto'` produce the same errors 😕

<details>
<summary>stack traces</summary>

```
Error: api/rss.xml is not prerenderable
    at render_endpoint (file:///Users/jasonkurian/src/github.com/jakxz/jakxz.github.io/.svelte-kit/output/server/index.js:461:11)
    at resolve2 (file:///Users/jasonkurian/src/github.com/jakxz/jakxz.github.io/.svelte-kit/output/server/index.js:2370:28)
    at async respond (file:///Users/jasonkurian/src/github.com/jakxz/jakxz.github.io/.svelte-kit/output/server/index.js:2429:12)
    at async globalThis.fetch (file:///Users/jasonkurian/src/github.com/jakxz/jakxz.github.io/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.465_qevq5tvhizyxp44gfhkn6m3ljq/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:130:21)
    at async load (file:///Users/jasonkurian/src/github.com/jakxz/jakxz.github.io/.svelte-kit/output/server/entries/pages/_layout.js:5:17)
    at async load_data (file:///Users/jasonkurian/src/github.com/jakxz/jakxz.github.io/.svelte-kit/output/server/index.js:1360:16)
    at async file:///Users/jasonkurian/src/github.com/jakxz/jakxz.github.io/.svelte-kit/output/server/index.js:1901:18
Error: api/posts.json is not prerenderable
    at render_endpoint (file:///Users/jasonkurian/src/github.com/jakxz/jakxz.github.io/.svelte-kit/output/server/index.js:461:11)
    at resolve2 (file:///Users/jasonkurian/src/github.com/jakxz/jakxz.github.io/.svelte-kit/output/server/index.js:2370:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async respond (file:///Users/jasonkurian/src/github.com/jakxz/jakxz.github.io/.svelte-kit/output/server/index.js:2429:12)
    at async globalThis.fetch (file:///Users/jasonkurian/src/github.com/jakxz/jakxz.github.io/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.465_qevq5tvhizyxp44gfhkn6m3ljq/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:130:21)
    at async load (file:///Users/jasonkurian/src/github.com/jakxz/jakxz.github.io/.svelte-kit/output/server/entries/pages/blog/_page.server.js:2:19)
    at async load_server_data (file:///Users/jasonkurian/src/github.com/jakxz/jakxz.github.io/.svelte-kit/output/server/index.js:1301:18)
    at async file:///Users/jasonkurian/src/github.com/jakxz/jakxz.github.io/.svelte-kit/output/server/index.js:1876:18
```

</details>

I think i'm landing [here](https://github.com/sveltejs/kit/blob/41ce0f2d91ef01ee6b6bb5143f8527751cdc65ce/packages/kit/src/runtime/server/endpoint.js#L32-L33) in the build step

I have also tried putting
```js
export const prerender = false;
```
in a `+layout.server.js`
and at the top of every one of the `api/` `+server.js` files with no luck.

With a bit of debugging it looks like my `state.prerendering` object in the `render_endpoint` method is:
```
{
  "dependencies": {}
}
```
essentially empty.

Curious if you've run into this or figured out a way around it? I've asked around on the svelte discord as well but got nothing yet.

**Comment by josh-collinsworth** [comment]
Hmmm this definitely looks like a breaking change in SvelteKit. I've toyed with it a bit but haven't been able to come up with a good solution. _Hopefully_ it's known to the SvelteKit team (and if you haven't already tried checking out the issues on the official SvelteKit repo, I would). But in any case, I'll see if I can find out more as soon as I'm able.

[Edit] I haven't tried it yet, but one potential solution that comes to mind might be to move the `+layout.js` file to a subfolder, so it doesn't load inside the `api` directory—or, probably better, implementing a layout reset inside of the API folder.  https://kit.svelte.dev/docs/advanced-routing#advanced-layouts-layout

**Comment by josh-collinsworth** [comment]
Still working on this. Really not sure what's going on but it appears to be a big change with how SvelteKit works with the static adapter. Can't get the site to build at all, and none too happy about it. Ugh. Pre-1.0 frameworks.

**Comment by josh-collinsworth** [comment]
Ok, so I've got the build working again. There were a few things going wrong:

1. Apparently, you can no longer use `url.params` in prerendered routes, which broke a lot of the API routes in this starter.
2. Also, it seems you now need to put `export const prerender = true` into _every_ `+server.js` file that you want to prerender; server routes don't inherit `prerender` from layouts. (EDIT: this seems to depend on what your server routes are doing and how they're called. I have a project where just adding `export const prerender = true` to the root `+layout.js` file was enough, and I have others where the server routes did _NOT_ inherit it, this one included. The docs mention the inheritance is conditional, but I haven't dug in enough to understand exactly what flips the switch.)
3. Finally, I ran into issues with a new rule in SvelteKit: you _cannot_ have a server route with sub-routes when prerendering. (e.g., there can't be both `api/posts` and `api/posts/count`.) If you try that, it will work on the dev server, but not in production. (The docs touch on this, but barely; they mention it's because there can't be both a file _and_ a folder with an identical name—`posts`, in this case.)

Anyway, to your question @JaKXz : If you _want_ your API routes to prerender, add `export const prerender = true` to your `+layout.js` file. If _that_ doesn't work, add that constant to each server route instead.

Otherwise, I believe you'll need to specify a fallback page and make the site run in SPA mode.

Hope that all helps!

**Comment by JaKXz** [comment]
Hey @josh-collinsworth thanks for the help, that worked great for a time. Unfortunately since sveltekit v503 (https://github.com/sveltejs/kit/commit/560394f5fded5033e99aebd1774b19cae13172da) the build step on HEAD [in this repo] is broken again... and I'm not quite following the discussion on some similar looking issues in the sveltekit issues 😓 https://github.com/sveltejs/kit/issues/7183 https://github.com/sveltejs/kit/issues/7244 

here's my [discord thread](https://discord.com/channels/457912077277855764/1029077841847001199) if you're curious. happy to open a new issue or continue the discussion here. thanks again!
