### ISSUE TITLE
`npm run build` fails on tip of main

### ISSUE THREAD

**Issue by TaborKelly** [josh-collinsworth/sveltekit-blog-starter#40]
I noticed that `npm run build` fails on the tip of main:

```
user@machine:/tmp$ git clone git@github.com:josh-collinsworth/sveltekit-blog-starter.git
Cloning into 'sveltekit-blog-starter'...
remote: Enumerating objects: 1290, done.
remote: Counting objects: 100% (413/413), done.
remote: Compressing objects: 100% (138/138), done.
remote: Total 1290 (delta 316), reused 275 (delta 275), pack-reused 877
Receiving objects: 100% (1290/1290), 884.28 KiB | 2.26 MiB/s, done.
Resolving deltas: 100% (663/663), done.
user@machine:/tmp$ cd sveltekit-blog-starter/
user@machine:/tmp/sveltekit-blog-starter$ npm install

added 207 packages, and audited 208 packages in 1s

52 packages are looking for funding
  run `npm fund` for details

1 high severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
user@machine:/tmp/sveltekit-blog-starter$ npm run build

> sveltekit-blog-starter@2.0.2 build
> vite build

vite v5.0.12 building SSR bundle for production...
✓ 119 modules transformed.
vite v5.0.12 building for production...
✓ 108 modules transformed.
.svelte-kit/output/client/_app/version.json                                               0.03 kB │ gzip:  0.05 kB
.svelte-kit/output/client/.vite/manifest.json                                             9.13 kB │ gzip:  1.02 kB
.svelte-kit/output/client/_app/immutable/chunks/each.-oqiv04n.js                          0.07 kB │ gzip:  0.09 kB
.svelte-kit/output/client/_app/immutable/chunks/index.oiCz_B55.js                         0.11 kB │ gzip:  0.12 kB
.svelte-kit/output/client/_app/immutable/nodes/11.pJKFA2UM.js                             0.19 kB │ gzip:  0.17 kB
.svelte-kit/output/client/_app/immutable/nodes/8.pJKFA2UM.js                              0.19 kB │ gzip:  0.17 kB
.svelte-kit/output/client/_app/immutable/chunks/config.9TwfRihT.js                        0.30 kB │ gzip:  0.22 kB
.svelte-kit/output/client/_app/immutable/chunks/control.pJ1mnnAb.js                       0.34 kB │ gzip:  0.21 kB
.svelte-kit/output/client/_app/immutable/chunks/Callout.G8ur-app.js                       0.74 kB │ gzip:  0.49 kB
.svelte-kit/output/client/_app/immutable/chunks/preload-helper.0HuHagjb.js                0.91 kB │ gzip:  0.56 kB
.svelte-kit/output/client/_app/immutable/nodes/1.SS8rTGE5.js                              1.42 kB │ gzip:  0.81 kB
.svelte-kit/output/client/_app/immutable/nodes/4._25Q4NZo.js                              1.44 kB │ gzip:  0.77 kB
.svelte-kit/output/client/_app/immutable/nodes/2.jcRJ92rD.js                              1.64 kB │ gzip:  0.87 kB
.svelte-kit/output/client/_app/immutable/nodes/6.CeOQR6v9.js                              1.83 kB │ gzip:  0.97 kB
.svelte-kit/output/client/_app/immutable/nodes/3.QeNnDV5Q.js                              1.99 kB │ gzip:  1.04 kB
.svelte-kit/output/client/_app/immutable/nodes/7.2_yB7NYC.js                              2.19 kB │ gzip:  1.15 kB
.svelte-kit/output/client/_app/immutable/chunks/mdsvex-component-example.11C05Tzm.js      2.34 kB │ gzip:  1.20 kB
.svelte-kit/output/client/_app/immutable/chunks/scheduler.Urk58y9q.js                     2.37 kB │ gzip:  1.12 kB
.svelte-kit/output/client/_app/immutable/nodes/12.fveUTNV4.js                             2.77 kB │ gzip:  1.33 kB
.svelte-kit/output/client/_app/immutable/nodes/10.Ap9OiEwe.js                             2.77 kB │ gzip:  1.33 kB
.svelte-kit/output/client/_app/immutable/chunks/singletons.yiWd7qOr.js                    2.98 kB │ gzip:  1.52 kB
.svelte-kit/output/client/_app/immutable/nodes/9.j_tp534v.js                              3.08 kB │ gzip:  1.47 kB
.svelte-kit/output/client/_app/immutable/nodes/13.B79RsLSY.js                             3.10 kB │ gzip:  1.41 kB
.svelte-kit/output/client/_app/immutable/chunks/heading-links-example.8k5nRDwS.js         3.27 kB │ gzip:  1.28 kB
.svelte-kit/output/client/_app/immutable/chunks/Pagination.qBPI-jEN.js                    4.82 kB │ gzip:  2.06 kB
.svelte-kit/output/client/_app/immutable/chunks/syntax-highlighting-example.QUXGYAwc.js   6.00 kB │ gzip:  1.93 kB
.svelte-kit/output/client/_app/immutable/nodes/5.0y2puOeF.js                              6.15 kB │ gzip:  2.59 kB
.svelte-kit/output/client/_app/immutable/entry/app.DfZb3kKz.js                            6.93 kB │ gzip:  2.37 kB
.svelte-kit/output/client/_app/immutable/chunks/index.GpMQ2F1a.js                         9.97 kB │ gzip:  4.21 kB
.svelte-kit/output/client/_app/immutable/nodes/0.Bp5Y4N42.js                             11.85 kB │ gzip:  4.30 kB
.svelte-kit/output/client/_app/immutable/chunks/README.4z_DNvg3.js                       21.19 kB │ gzip:  7.48 kB
.svelte-kit/output/client/_app/immutable/entry/start.NyYNPe7Q.js                         27.86 kB │ gzip: 11.20 kB
✓ built in 590ms
  301 /blog/page -> /blog
  301 /blog/category/*/page/* -> /blog/category/*
  301 /blog/category/page/* -> /blog
  301 /blog/page/* -> /blog
SvelteKitError: Not found: /example.com/api/rss.xml
    at resolve2 (file:///tmp/sveltekit-blog-starter/.svelte-kit/output/server/index.js:2831:18)
    at resolve (file:///tmp/sveltekit-blog-starter/.svelte-kit/output/server/index.js:2663:34)
    at #options.hooks.handle (file:///tmp/sveltekit-blog-starter/.svelte-kit/output/server/index.js:2905:71)
    at respond (file:///tmp/sveltekit-blog-starter/.svelte-kit/output/server/index.js:2661:43) {
  status: 404,
  text: 'Not Found'
}

node:internal/event_target:1100
  process.nextTick(() => { throw err; });
                           ^
Error: 404 /example.com/api/rss.xml (linked from /)
To suppress or handle this error, implement `handleHttpError` in https://kit.svelte.dev/docs/configuration#prerender
    at file:///tmp/sveltekit-blog-starter/node_modules/@sveltejs/kit/src/core/config/options.js:201:13
    at file:///tmp/sveltekit-blog-starter/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:64:25
    at save (file:///tmp/sveltekit-blog-starter/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:399:4)
    at visit (file:///tmp/sveltekit-blog-starter/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:232:3)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:326:10)
    at [kOnMessage] (node:internal/worker:337:37)
    at MessagePort.<anonymous> (node:internal/worker:232:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:826:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)

Node.js v20.11.0
user@machine:/tmp/sveltekit-blog-starter$
```

This does not happen with `5360246f6a30efa5ab0895033af7f1815b036aa2`.

**Comment by josh-collinsworth** [comment]
Fixed in latest. Thanks for reporting!

Looks like without an `http://` protocol, the link was being misread as relative and failing the build.
