### ISSUE TITLE
npm run build issue

### ISSUE THREAD

**Issue by eyal-gor** [josh-collinsworth/sveltekit-blog-starter#43]
```
velte-kit/output/client/_app/immutable/nodes/5.lgHxx4ap.js                                      6.84 kB │ gzip:  2.72 kB
.svelte-kit/output/client/_app/immutable/entry/app.6DZ-rLV4.js                                    6.93 kB │ gzip:  2.36 kB
.svelte-kit/output/client/_app/immutable/chunks/index.T8xtbQjq.js                                 9.97 kB │ gzip:  4.21 kB
.svelte-kit/output/client/_app/immutable/nodes/0.u6SMy1NS.js                                     11.77 kB │ gzip:  4.32 kB
.svelte-kit/output/client/_app/immutable/chunks/README.qbVoyzal.js                               21.19 kB │ gzip:  7.48 kB
.svelte-kit/output/client/_app/immutable/entry/start.dDGYyjlR.js                                 27.86 kB │ gzip: 11.20 kB
✓ built in 2.45s
  301 /blog/page -> /blog
  301 /blog/category/*/page/* -> /blog/category/*
  301 /blog/category/page/* -> /blog
  301 /blog/page/* -> /blog
SvelteKitError: Not found: /eyal.com/api/rss.xml
    at resolve2 (file:///Users/eyal/Code/p_35_blog/.svelte-kit/output/server/index.js:2831:18)
    at resolve (file:///Users/eyal/Code/p_35_blog/.svelte-kit/output/server/index.js:2663:34)
    at #options.hooks.handle (file:///Users/eyal/Code/p_35_blog/.svelte-kit/output/server/index.js:2905:71)
    at respond (file:///Users/eyal/Code/p_35_blog/.svelte-kit/output/server/index.js:2661:43) {
  status: 404,
  text: 'Not Found'
}

node:internal/event_target:1062
  process.nextTick(() => { throw err; });
                           ^
Error: 404 /eyal.com/api/rss.xml (linked from /)
To suppress or handle this error, implement `handleHttpError` in https://kit.svelte.dev/docs/configuration#prerender
    at file:///Users/eyal/Code/p_35_blog/node_modules/@sveltejs/kit/src/core/config/options.js:201:13
    at file:///Users/eyal/Code/p_35_blog/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:64:25
```

I'm getting the rss.xml error - any idea why? I do have the rountes/api/rss.xml/+server.js file in place (unchanged)

![Screenshot 2024-03-14 at 17 47 57](https://github.com/josh-collinsworth/sveltekit-blog-starter/assets/1525119/03bff284-aaf8-4f5b-9fe7-0e5084f6b651)

**Comment by eyal-gor** [comment]
fixed after updated repo
